//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToModels.v3.2 (entitiesToModels.codeplex.com).
//     Timestamp: 2016/02/20 - 17:52:55
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using HelpDeskApp.Common.Models;
using HelpDeskApp.Entity;

namespace HelpDeskApp.Library.Helpers
{

    /// <summary>
    /// Assembler for <see cref="DEPARTAMENTOS"/> and <see cref="Departamentos"/>.
    /// </summary>
    public static partial class DepartamentosHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToModel"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="Departamentos"/> converted from <see cref="DEPARTAMENTOS"/>.</param>
        static partial void OnDTO(this DEPARTAMENTOS entity, Departamentos dto);

        /// <summary>
        /// Invoked when <see cref="ToTable"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="DEPARTAMENTOS"/> converted from <see cref="Departamentos"/>.</param>
        static partial void OnEntity(this Departamentos dto, DEPARTAMENTOS entity);

        /// <summary>
        /// Converts this instance of <see cref="Departamentos"/> to an instance of <see cref="DEPARTAMENTOS"/>.
        /// </summary>
        /// <param name="dto"><see cref="Departamentos"/> to convert.</param>
        public static DEPARTAMENTOS ToTable(this Departamentos dto)
        {
            if (dto == null) return null;

            var entity = new DEPARTAMENTOS();

            entity.Id = dto.Id;
            entity.Descripcion = dto.Descripcion;
            entity.Fecha_Creacion = DateTime.Now;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="DEPARTAMENTOS"/> to an instance of <see cref="Departamentos"/>.
        /// </summary>
        /// <param name="entity"><see cref="DEPARTAMENTOS"/> to convert.</param>
        public static Departamentos ToModel(this DEPARTAMENTOS entity)
        {
            if (entity == null) return null;

            var dto = new Departamentos();

            dto.Id = entity.Id;
            dto.Descripcion = entity.Descripcion;
            dto.Fecha_Creacion = entity.Fecha_Creacion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="Departamentos"/> to an instance of <see cref="DEPARTAMENTOS"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<DEPARTAMENTOS> ToTables(this IEnumerable<Departamentos> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToTable()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="DEPARTAMENTOS"/> to an instance of <see cref="Departamentos"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<Departamentos> ToModels(this IEnumerable<DEPARTAMENTOS> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToModel()).ToList();
        }

        public static bool Save(Departamentos model)
        {
            bool result;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                

                try
                {
                    context.DEPARTAMENTOS.Add(model.ToTable());
                    context.SaveChanges();
                    result = true;
                }
                catch (Exception)
                {

                    result = false;
                }

            }

            return result;
        }

        public static List<Departamentos> GetAll()
        {
            List<Departamentos> list;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.DEPARTAMENTOS.ToList();
                list = queryResult.Count > 0 ? ToModels(queryResult) : new List<Departamentos>();
            }
            return list;
        }

        public static Departamentos GetDivisionByPrimaryKey(int Id)
        {
            Departamentos Obj;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.DEPARTAMENTOS.SingleOrDefault(a => a.Id == Id);
                Obj = ToModel(queryResult);
            }
            return Obj;

        }

    }
}
