//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToModels.v3.2 (entitiesToModels.codeplex.com).
//     Timestamp: 2016/02/20 - 17:52:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using HelpDeskApp.Common.Models;
using HelpDeskApp.Entity;

namespace HelpDeskApp.Library.Helpers
{

    /// <summary>
    /// Assembler for <see cref="ESTATUS"/> and <see cref="Estatus"/>.
    /// </summary>
    public static partial class EstatusHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToModel"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="Estatus"/> converted from <see cref="ESTATUS"/>.</param>
        static partial void OnDTO(this ESTATUS entity, Estatus dto);

        /// <summary>
        /// Invoked when <see cref="ToTable"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="ESTATUS"/> converted from <see cref="Estatus"/>.</param>
        static partial void OnEntity(this Estatus dto, ESTATUS entity);

        /// <summary>
        /// Converts this instance of <see cref="Estatus"/> to an instance of <see cref="ESTATUS"/>.
        /// </summary>
        /// <param name="dto"><see cref="Estatus"/> to convert.</param>
        public static ESTATUS ToTable(this Estatus dto)
        {
            if (dto == null) return null;

            var entity = new ESTATUS();

            entity.Id = dto.Id;
            entity.Descripcion = dto.Descripcion;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="ESTATUS"/> to an instance of <see cref="Estatus"/>.
        /// </summary>
        /// <param name="entity"><see cref="ESTATUS"/> to convert.</param>
        public static Estatus ToModel(this ESTATUS entity)
        {
            if (entity == null) return null;

            var dto = new Estatus();

            dto.Id = entity.Id;
            dto.Descripcion = entity.Descripcion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="Estatus"/> to an instance of <see cref="ESTATUS"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<ESTATUS> ToTables(this IEnumerable<Estatus> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToTable()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="ESTATUS"/> to an instance of <see cref="Estatus"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<Estatus> ToModels(this IEnumerable<ESTATUS> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToModel()).ToList();
        }

        public static bool Save(Estatus model)
        {
            bool result;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                

                try
                {
                    context.ESTATUS.Add(model.ToTable());
                    context.SaveChanges();
                    result = true;
                }
                catch (Exception)
                {

                    result = false;
                }

            }

            return result;
        }

        public static List<Estatus> GetAll()
        {
            List<Estatus> list;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.ESTATUS.ToList();
                list = queryResult.Count > 0 ? ToModels(queryResult) : new List<Estatus>();
            }
            return list;
        }

        public static Estatus GetEstatusByPrimaryKey(int Id)
        {
            Estatus Obj;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.ESTATUS.SingleOrDefault(a => a.Id == Id);
                Obj = ToModel(queryResult);
            }
            return Obj;

        }

    }
}
