//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToModels.v3.2 (entitiesToModels.codeplex.com).
//     Timestamp: 2016/02/20 - 17:52:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using HelpDeskApp.Common.Models;
using HelpDeskApp.Entity;

namespace HelpDeskApp.Library.Helpers
{

    /// <summary>
    /// Assembler for <see cref="ISSUES"/> and <see cref="Issues"/>.
    /// </summary>
    public static partial class IssuesHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToModel"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="Issues"/> converted from <see cref="ISSUES"/>.</param>
        static partial void OnDTO(this ISSUES entity, Issues dto);

        /// <summary>
        /// Invoked when <see cref="ToTable"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="ISSUES"/> converted from <see cref="Issues"/>.</param>
        static partial void OnEntity(this Issues dto, ISSUES entity);

        /// <summary>
        /// Converts this instance of <see cref="Issues"/> to an instance of <see cref="ISSUES"/>.
        /// </summary>
        /// <param name="dto"><see cref="Issues"/> to convert.</param>
        public static ISSUES ToTable(this Issues dto)
        {
            if (dto == null) return null;

            var entity = new ISSUES();

            entity.Id = dto.Id;
            entity.Descripcion = dto.Descripcion;
            entity.Fecha_Creacion = DateTime.Now;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="ISSUES"/> to an instance of <see cref="Issues"/>.
        /// </summary>
        /// <param name="entity"><see cref="ISSUES"/> to convert.</param>
        public static Issues ToModel(this ISSUES entity)
        {
            if (entity == null) return null;

            var dto = new Issues();

            dto.Id = entity.Id;
            dto.Descripcion = entity.Descripcion;
            dto.Fecha_Creacion = entity.Fecha_Creacion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="Issues"/> to an instance of <see cref="ISSUES"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<ISSUES> ToTables(this IEnumerable<Issues> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToTable()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="ISSUES"/> to an instance of <see cref="Issues"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<Issues> ToModels(this IEnumerable<ISSUES> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToModel()).ToList();
        }

        public static bool Save(Issues model)
        {
            bool result;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                

                try
                {
                    context.ISSUES.Add(model.ToTable());
                    context.SaveChanges();
                    result = true;
                }
                catch (Exception)
                {

                    result = false;
                }

            }

            return result;
        }

        public static List<Issues> GetAll()
        {
            List<Issues> list;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.ISSUES.ToList();
                list = queryResult.Count > 0 ? ToModels(queryResult) : new List<Issues>();
            }
            return list;
        }

        public static Issues GetIssueByPrimaryKey(int Id)
        {
            Issues Obj;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.ISSUES.SingleOrDefault(a => a.Id == Id);
                Obj = ToModel(queryResult);
            }
            return Obj;

        }

    }
}
