//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToModels.v3.2 (entitiesToModels.codeplex.com).
//     Timestamp: 2016/02/20 - 17:52:56
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using HelpDeskApp.Common.Models;
using HelpDeskApp.Entity;

namespace HelpDeskApp.Library.Helpers
{

    /// <summary>
    /// Assembler for <see cref="PREGUNTAS"/> and <see cref="Preguntas"/>.
    /// </summary>
    public static partial class PreguntasHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToModel"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="Preguntas"/> converted from <see cref="PREGUNTAS"/>.</param>
        static partial void OnDTO(this PREGUNTAS entity, Preguntas dto);

        /// <summary>
        /// Invoked when <see cref="ToTable"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="PREGUNTAS"/> converted from <see cref="Preguntas"/>.</param>
        static partial void OnEntity(this Preguntas dto, PREGUNTAS entity);

        /// <summary>
        /// Converts this instance of <see cref="Preguntas"/> to an instance of <see cref="PREGUNTAS"/>.
        /// </summary>
        /// <param name="dto"><see cref="Preguntas"/> to convert.</param>
        public static PREGUNTAS ToTable(this Preguntas dto)
        {
            if (dto == null) return null;

            var entity = new PREGUNTAS();

            entity.Id = dto.Id;
            entity.Descripcion = dto.Descripcion;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="PREGUNTAS"/> to an instance of <see cref="Preguntas"/>.
        /// </summary>
        /// <param name="entity"><see cref="PREGUNTAS"/> to convert.</param>
        public static Preguntas ToModel(this PREGUNTAS entity)
        {
            if (entity == null) return null;

            var dto = new Preguntas();

            dto.Id = entity.Id;
            dto.Descripcion = entity.Descripcion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="Preguntas"/> to an instance of <see cref="PREGUNTAS"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<PREGUNTAS> ToTables(this IEnumerable<Preguntas> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToTable()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="PREGUNTAS"/> to an instance of <see cref="Preguntas"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<Preguntas> ToModels(this IEnumerable<PREGUNTAS> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToModel()).ToList();
        }

        public static bool Save(Preguntas model)
        {
            bool result;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                

                try
                {
                    context.PREGUNTAS.Add(model.ToTable());
                    context.SaveChanges();
                    result = true;
                }
                catch (Exception)
                {

                    result = false;
                }

            }

            return result;
        }

        public static List<Preguntas> GetAll()
        {
            List<Preguntas> list;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.PREGUNTAS.ToList();
                list = queryResult.Count > 0 ? ToModels(queryResult) : new List<Preguntas>();
            }
            return list;
        }

        public static Preguntas GetPreguntaByPrimaryKey(int Id)
        {
            Preguntas Obj;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.PREGUNTAS.SingleOrDefault(a => a.Id == Id);
                Obj = ToModel(queryResult);
            }
            return Obj;

        }

    }
}
