//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToModels.v3.2 (entitiesToModels.codeplex.com).
//     Timestamp: 2016/02/20 - 17:52:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using HelpDeskApp.Common.Models;
using HelpDeskApp.Entity;

namespace HelpDeskApp.Library.Helpers
{

    /// <summary>
    /// Assembler for <see cref="TICKETS_RESPUESTA"/> and <see cref="Tickets_Respuesta"/>.
    /// </summary>
    public static partial class Tickets_RespuestaHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToModel"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="Tickets_Respuesta"/> converted from <see cref="TICKETS_RESPUESTA"/>.</param>
        static partial void OnDTO(this TICKETS_RESPUESTA entity, Tickets_Respuesta dto);

        /// <summary>
        /// Invoked when <see cref="ToTable"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="TICKETS_RESPUESTA"/> converted from <see cref="Tickets_Respuesta"/>.</param>
        static partial void OnEntity(this Tickets_Respuesta dto, TICKETS_RESPUESTA entity);

        /// <summary>
        /// Converts this instance of <see cref="Tickets_Respuesta"/> to an instance of <see cref="TICKETS_RESPUESTA"/>.
        /// </summary>
        /// <param name="dto"><see cref="Tickets_Respuesta"/> to convert.</param>
        public static TICKETS_RESPUESTA ToTable(this Tickets_Respuesta dto)
        {
            if (dto == null) return null;

            var entity = new TICKETS_RESPUESTA();

            entity.IdTickets = dto.IdTickets;
            entity.IdPregunta = dto.IdPregunta;
            entity.Respuesta = dto.Respuesta;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="TICKETS_RESPUESTA"/> to an instance of <see cref="Tickets_Respuesta"/>.
        /// </summary>
        /// <param name="entity"><see cref="TICKETS_RESPUESTA"/> to convert.</param>
        public static Tickets_Respuesta ToModel(this TICKETS_RESPUESTA entity)
        {
            if (entity == null) return new Tickets_Respuesta();

            var dto = new Tickets_Respuesta();

            dto.IdTickets = entity.IdTickets;
            dto.IdPregunta = entity.IdPregunta;
            dto.Respuesta = entity.Respuesta;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="Tickets_Respuesta"/> to an instance of <see cref="TICKETS_RESPUESTA"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<TICKETS_RESPUESTA> ToTables(this IEnumerable<Tickets_Respuesta> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToTable()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="TICKETS_RESPUESTA"/> to an instance of <see cref="Tickets_Respuesta"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<Tickets_Respuesta> ToModels(this IEnumerable<TICKETS_RESPUESTA> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToModel()).ToList();
        }

        public static bool Save(Tickets_Respuesta model)
        {
            bool result;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                try
                {
                    context.TICKETS_RESPUESTA.Add(model.ToTable());
                    context.SaveChanges();
                    result = true;
                }
                catch (Exception)
                {

                    result = false;
                }

            }

            return result;
        }

        public static List<Tickets_Respuesta> GetAll()
        {
            List<Tickets_Respuesta> list;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.TICKETS_RESPUESTA.ToList();
                list = queryResult.Count > 0 ? ToModels(queryResult) : new List<Tickets_Respuesta>();
            }
            return list;
        }

        public static Tickets_Respuesta GetTicketsRespuestaByPrimaryKey(int IdTicket, int IdPregunta)
        {
            Tickets_Respuesta Obj;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.TICKETS_RESPUESTA.SingleOrDefault(a => a.IdTickets == IdTicket && a.IdPregunta == IdPregunta);
                Obj = ToModel(queryResult);
            }
            return Obj;

        }

    }
}
