//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToModels.v3.2 (entitiesToModels.codeplex.com).
//     Timestamp: 2016/02/20 - 17:52:57
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;
using System.Linq;
using HelpDeskApp.Common.Models;
using HelpDeskApp.Entity;

namespace HelpDeskApp.Library.Helpers
{

    /// <summary>
    /// Assembler for <see cref="USER_FOLLOWED_USER"/> and <see cref="User_Followed_User"/>.
    /// </summary>
    public static partial class User_Followed_UserHelper
    {
        /// <summary>
        /// Invoked when <see cref="ToModel"/> operation is about to return.
        /// </summary>
        /// <param name="dto"><see cref="User_Followed_User"/> converted from <see cref="USER_FOLLOWED_USER"/>.</param>
        static partial void OnDTO(this USER_FOLLOWED_USER entity, User_Followed_User dto);

        /// <summary>
        /// Invoked when <see cref="ToTable"/> operation is about to return.
        /// </summary>
        /// <param name="entity"><see cref="USER_FOLLOWED_USER"/> converted from <see cref="User_Followed_User"/>.</param>
        static partial void OnEntity(this User_Followed_User dto, USER_FOLLOWED_USER entity);

        /// <summary>
        /// Converts this instance of <see cref="User_Followed_User"/> to an instance of <see cref="USER_FOLLOWED_USER"/>.
        /// </summary>
        /// <param name="dto"><see cref="User_Followed_User"/> to convert.</param>
        public static USER_FOLLOWED_USER ToTable(this User_Followed_User dto)
        {
            if (dto == null) return null;

            var entity = new USER_FOLLOWED_USER();

            entity.UserID = dto.UserID;
            entity.UserIdFollowed = dto.UserIdFollowed;
            entity.Fecha_Creacion = dto.Fecha_Creacion;

            dto.OnEntity(entity);

            return entity;
        }

        /// <summary>
        /// Converts this instance of <see cref="USER_FOLLOWED_USER"/> to an instance of <see cref="User_Followed_User"/>.
        /// </summary>
        /// <param name="entity"><see cref="USER_FOLLOWED_USER"/> to convert.</param>
        public static User_Followed_User ToModel(this USER_FOLLOWED_USER entity)
        {
            if (entity == null) return new User_Followed_User();

            var dto = new User_Followed_User();

            dto.UserID = entity.UserID;
            dto.UserIdFollowed = entity.UserIdFollowed;
            dto.Fecha_Creacion = entity.Fecha_Creacion;

            entity.OnDTO(dto);

            return dto;
        }

        /// <summary>
        /// Converts each instance of <see cref="User_Followed_User"/> to an instance of <see cref="USER_FOLLOWED_USER"/>.
        /// </summary>
        /// <param name="dtos"></param>
        /// <returns></returns>
        public static List<USER_FOLLOWED_USER> ToTables(this IEnumerable<User_Followed_User> dtos)
        {
            if (dtos == null) return null;

            return dtos.Select(e => e.ToTable()).ToList();
        }

        /// <summary>
        /// Converts each instance of <see cref="USER_FOLLOWED_USER"/> to an instance of <see cref="User_Followed_User"/>.
        /// </summary>
        /// <param name="entities"></param>
        /// <returns></returns>
        public static List<User_Followed_User> ToModels(this IEnumerable<USER_FOLLOWED_USER> entities)
        {
            if (entities == null) return null;

            return entities.Select(e => e.ToModel()).ToList();
        }

        public static bool Save(User_Followed_User model)
        {
            bool result;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                try
                {
                    context.USER_FOLLOWED_USER.Add(model.ToTable());
                    context.SaveChanges();
                    result = true;
                }
                catch (Exception)
                {

                    result = false;
                }

            }

            return result;
        }

        public static List<User_Followed_User> GetAll()
        {
            List<User_Followed_User> list;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.USER_FOLLOWED_USER.ToList();
                list = queryResult.Count > 0 ? ToModels(queryResult) : new List<User_Followed_User>();
            }
            return list;
        }

        public static User_Followed_User GetUserGroupsByPrimaryKey(int UserId, int UserIdFollowed)
        {
            User_Followed_User Obj;

            using (HelpDeskApfEntities context = new HelpDeskApfEntities())
            {
                var queryResult = context.USER_FOLLOWED_USER.SingleOrDefault(a => a.UserID == UserId && a.UserIdFollowed == UserIdFollowed);
                Obj = ToModel(queryResult);
            }
            return Obj;

        }

        //Todo: Get de Los usuarios seguidos por un usuario

    }
}
