//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/20 - 17:52:54
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HelpDeskApp.Common.Models
{
    [DataContract()]
    public partial class User_Groups
    {
        [DataMember()]
        public Int32 UserId { get; set; }

        [DataMember()]
        public Int32 GroupId { get; set; }

        public User_Groups()
        {
        }

        public User_Groups(Int32 userId, Int32 groupId)
        {
			this.UserId = userId;
			this.GroupId = groupId;
        }
    }
}
