//-------------------------------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by EntitiesToDTOs.v3.2 (entitiestodtos.codeplex.com).
//     Timestamp: 2016/02/25 - 02:52:32
//
//     Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//-------------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Runtime.Serialization;
using System.Text;

namespace HelpDeskApp.Common.Models
{
    [DataContract()]
    public partial class USUARIOS_
    {
        [DataMember()]
        public Int32 id { get; set; }

        [DataMember()]
        public String PrimerNombre { get; set; }

        [DataMember()]
        public String SegundoNombre { get; set; }

        [DataMember()]
        public String PrimerApellido { get; set; }

        [DataMember()]
        public String SegundoApellido { get; set; }

        [DataMember()]
        public String Usuario { get; set; }

        [DataMember()]
        public DateTime Fecha_creacion { get; set; }

        public USUARIOS_()
        {
        }

        public USUARIOS_(Int32 id, String primerNombre, String segundoNombre, String primerApellido, String segundoApellido, String usuario, DateTime fecha_creacion)
        {
			this.id = id;
			this.PrimerNombre = primerNombre;
			this.SegundoNombre = segundoNombre;
			this.PrimerApellido = primerApellido;
			this.SegundoApellido = segundoApellido;
			this.Usuario = usuario;
			this.Fecha_creacion = fecha_creacion;
        }
    }
}
