//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskApp.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class HelpDeskApfEntities : DbContext
    {
        public HelpDeskApfEntities()
            : base("name=HelpDeskApfEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<DEPARTAMENTOS> DEPARTAMENTOS { get; set; }
        public DbSet<DIVISION> DIVISION { get; set; }
        public DbSet<ESTATUS> ESTATUS { get; set; }
        public DbSet<GRUPOS> GRUPOS { get; set; }
        public DbSet<ISSUES> ISSUES { get; set; }
        public DbSet<ORGANIZACION> ORGANIZACION { get; set; }
        public DbSet<PREGUNTAS> PREGUNTAS { get; set; }
        public DbSet<PRIORIDAD> PRIORIDAD { get; set; }
        public DbSet<TICKETS> TICKETS { get; set; }
        public DbSet<TICKETS_RESPUESTA> TICKETS_RESPUESTA { get; set; }
        public DbSet<USER_FOLLOWED_USER> USER_FOLLOWED_USER { get; set; }
        public DbSet<USER_GROUPS> USER_GROUPS { get; set; }
        public DbSet<UserProfile> UserProfile { get; set; }
        public DbSet<USUARIOS> USUARIOS { get; set; }
        public DbSet<webpages_Membership> webpages_Membership { get; set; }
        public DbSet<webpages_OAuthMembership> webpages_OAuthMembership { get; set; }
        public DbSet<webpages_Roles> webpages_Roles { get; set; }
    
        public virtual ObjectResult<SPC_GET_ALL_TICKETS_WITH_DESCRIP_Result> SPC_GET_ALL_TICKETS_WITH_DESCRIP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPC_GET_ALL_TICKETS_WITH_DESCRIP_Result>("SPC_GET_ALL_TICKETS_WITH_DESCRIP");
        }
    
        public virtual ObjectResult<SPC_GET_TICKET_BY_USR_REQUEST_Result> SPC_GET_TICKET_BY_USR_REQUEST(string uSUARIO)
        {
            var uSUARIOParameter = uSUARIO != null ?
                new ObjectParameter("USUARIO", uSUARIO) :
                new ObjectParameter("USUARIO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<SPC_GET_TICKET_BY_USR_REQUEST_Result>("SPC_GET_TICKET_BY_USR_REQUEST", uSUARIOParameter);
        }
    }
}
